# Generated by Django 4.2.30 on 2026-05-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('confirm_pass', models.CharField(max_length=10)),
                ('terms', models.CharField(max_length=10)),
            ],
        ),
    ]
