# Generated by Django 4.2.30 on 2026-05-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserReg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
