# Generated by Django 4.2.30 on 2026-05-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserReg', '0002_reguser_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
