# Generated by Django 4.2.30 on 2026-05-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserReg', '0003_reguser_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='last_reset_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reguser',
            name='reset_request_count',
            field=models.IntegerField(default=0),
        ),
    ]
