# Generated by Django 4.2.30 on 2026-06-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserReg', '0004_reguser_last_reset_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
