# Generated by Django 4.2.30 on 2026-06-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserReg', '0005_reguser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
