# Generated by Django 4.2.30 on 2026-06-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserReg', '0006_reguser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='confirm_pass',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
