# Generated by Django 4.2.30 on 2026-06-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserReg', '0007_alter_reguser_confirm_pass_alter_reguser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='confirm_pass',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
