# Generated by Django 5.2.8 on 2026-05-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_icon', models.CharField(max_length=50)),
                ('course_titile', models.CharField(max_length=50)),
                ('course_desc', models.TextField()),
                ('course_price', models.CharField(max_length=10)),
                ('course_duration', models.CharField(max_length=10)),
            ],
        ),
    ]
