# Generated by Django 4.2.30 on 2026-05-08 03:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
