# Generated by Django 4.2.30 on 2026-05-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_courses_course_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_titile',
            new_name='course_title',
        ),
    ]
