# Generated by Django 4.2.30 on 2026-05-15 03:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_course_titile_courses_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='course_title', unique=True),
        ),
    ]
