# Generated by Django 4.2.30 on 2026-05-15 04:05

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='notification_title', unique=True)),
                ('notification_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
