# Generated by Django 4.2.30 on 2026-05-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='notification_title',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
